---
- hosts: all
  gather_facts: false
  tasks:
    - name: List Files
      shell: ls .
      register: file_list
    - name: Show List of Files
      debug:
        msg: "{{ file_list.stdout_lines }}"
    - name: facts
      set_fact:
        greeting_var: hello
        goodbye_var: goodbye
    - name: Say Hello
      debug:
        msg: "{{ greeting_var }} world!"
    - name: Say Goodbye
      debug:
        msg: "{{ goodbye_var }} world!"
    - include_role:
        name: hello